agroplace/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.urls import path
from agroplace.apps.system.views import home
from agroplace.apps.users.views import register, login
from agroplace.apps.orders.views import cart, orders
from agroplace.apps.products.views import product, category

admin.autodiscover()
admin.site.site_header = 'AGROPLACE - ADMINISTRATION'
admin.site.site_title = 'AGROPLACE - ADMINISTRATION'

urlpatterns = i18n_patterns(
    url(r'^admin/', admin.site.urls),
    # path('i18n/', include('django.conf.urls.i18n')),

    url(r'^register/$', register, name='register'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^cart/$', cart, name='cart'),
    url(r'^orders/$', orders, name='orders'),
    url(r'^product/(?P<pk>\d+)/$', product, name='product'),
    url(r'^category/$', category, name='category_all'),
    url(r'^category/(?P<pk>\d+)/$', category, name='category'),
    url(r'^$', home, name='home'),
    prefix_default_language=False
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agroplace/apps/orders/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Orders(models.Model):
    """ Model of orders. """
    ORDERS_STATUSES = [
        [-1, _("Error on payment")],
        [0, _("Awaiting payment")],
        [1, _("In process")],
        [2, _("Handed over to the courier")],
        [3, _("Delivered")],
    ]
    user = models.ForeignKey('users.Users', on_delete=models.SET_NULL, null=True)
    comment = models.TextField(blank=True, null=True)
    country = models.CharField(max_length=128, blank=True, null=True)
    region = models.CharField(max_length=255, blank=True, null=True)
    postal_code = models.PositiveIntegerField(blank=True, null=True)
    status = models.PositiveSmallIntegerField(choices=ORDERS_STATUSES, default=0)
    date = models.DateTimeField(auto_now_add=True)

    def total_cost(self) -> float:
        offerings = ProductsInOrders.objects.filter(order=self)
        total = 0
        for ofrng in offerings:
            total += ofrng.get_total_cost()
        return total

    def products(self):
        return ProductsInOrders.objects.filter(order=self)


class ProductsInOrders(models.Model):
    """ Model of Products in order. """

    order = models.ForeignKey(Orders, on_delete=models.CASCADE)
    product = models.ForeignKey('products.Products', on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    qty = models.PositiveIntegerField(default=1)
    cost = models.FloatField()

    def get_total_cost(self) -> float:
        return self.cost*self.qty


class Cart(models.Model):
    user = models.ForeignKey('users.Users', on_delete=models.CASCADE)
    product = models.ForeignKey('products.Products', on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1)
    # cost = models.FloatField()
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = [['user', 'product']]

agroplace/apps/products/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from agroplace.functions import get_random_code


def cats_banner_images_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    imagename = get_random_code(6).lower()
    # file will be uploaded to MEDIA_ROOT/images/<product_id>/<filename>
    return 'cats_images/{0}/{1}'.format(instance.id, '{}.{}'.format(imagename, ext))


class Categories(models.Model):
    name = models.CharField(max_length=250)
    banner_image = models.ImageField(upload_to=cats_banner_images_directory_path)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.name


def products_images_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    imagename = get_random_code(6).lower()
    # file will be uploaded to MEDIA_ROOT/images/<product_id>/<filename>
    return 'products/{0}/{1}'.format(instance.id, '{}.{}'.format(imagename, ext))


class Products(models.Model):
    MEASUREMENTS = [
        ['peace', _("Peace")],
        ['kg', _("Kilogram")],
        ['t', _("Tonne")],
        ['l', _("Liter")],
        ['bag', _("Bag")],  # Мешок
    ]

    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    cost = models.FloatField()
    image = models.ImageField(upload_to=products_images_directory_path)
    category = models.ForeignKey(Categories, on_delete=models.SET_NULL, null=True, blank=True)
    measurement = models.CharField(max_length=16, choices=MEASUREMENTS, default='peace')
    min_qty = models.PositiveSmallIntegerField(default=1)
    status = models.BooleanField(default=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

agroplace/apps/orders/views.py
from django.shortcuts import render, redirect
from django import forms
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext_lazy as _

from agroplace.apps.orders.models import Orders, Cart, ProductsInOrders


class OrdersForm(forms.ModelForm):
    class Meta:
        model = Orders
        fields = ['comment', 'country', 'region', 'postal_code']

    def clean(self):
        form_data = self.cleaned_data
        if not get_cart_count(self.user):
            raise forms.ValidationError("Products are not found")
            # self._errors[None] = ["Password do not match"]  # Will raise a error message
        return form_data


def get_cart_count(user) -> int:
    cart_count = 0
    if user.is_authenticated:
        cart_count = Cart.objects.filter(user=user).count()
    return cart_count


@login_required(login_url='/login')
def cart(request):
    cart = Cart.objects.filter(user=request.user)
    if request.method == "POST":
        form = OrdersForm(request.POST)
        form.user = request.user

        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            new_order = post.save()
            for c in cart:
                ProductsInOrders.objects.create(
                    order=post,
                    product=c.product,
                    cost=c.product.cost,
                    name=c.product.name,
                    qty=c.qty
                )
            cart.delete()
            return redirect('/orders')
    else:
        order_form = OrdersForm()

    # cart = Cart.objects.filter(user=request.user)
    if request.GET.get('delete'):
        Cart.objects.filter(product_id=request.GET['delete'], user=request.user).delete()

    cart_count = get_cart_count(request.user)
    page_title = _('Cart')
    return render(request, 'pages/cart.html', locals())


@login_required(login_url='/login')
def orders(request):
    user_orders = Orders.objects.filter(user=request.user).order_by('-id')
    cart_count = get_cart_count(request.user)
    page_title = _('My orders')
    return render(request, 'pages/orders.html', locals())

agroplace/apps/products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.translation import gettext_lazy as _

from .models import Products, Categories
from agroplace.apps.orders.models import Cart


def product(request, pk):

    product = get_object_or_404(Products, id=pk)
    related = Products.objects.filter(status=1).exclude(id=product.id).order_by('?')
    page_title = product.name
    if request.method == "POST":
        if not request.user.is_authenticated:
            return redirect('/login/?next=/product/{}/'.format(product.id))
        if Products.objects.filter(id=request.POST['product_id']).exists():
            existed, new = Cart.objects.get_or_create(product_id=request.POST['product_id'], user=request.user)
            if existed:
                existed.qty += int(request.POST['quantity'])
                existed.save()
            elif new:
                new.qty = int(request.POST['quantity'])
                new.save()
            product_added_tocart = True


    if request.user.is_authenticated:
        cart_count = Cart.objects.filter(user=request.user).count()
    return render(request, 'pages/product.html', locals())


def category(request, pk=None):
    if request.user.is_authenticated:
        cart_count = Cart.objects.filter(user=request.user).count()

    main_cats = Categories.objects.filter(status=True)
    if pk:
        category = get_object_or_404(Categories, id=pk)
        products = Products.objects.filter(status=1, category=category)
        page_title = category.name
    else:
        category = None
        products = Products.objects.filter(status=1)
        page_title = _("Our products")

    return render(request, 'pages/category.html', locals())

templates/pages/cart.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}
<section class="ftco-section ftco-cart ftco-no-pt">
			<div class="container">
				<div class="row">
    			<div class="col-md-12 ftco-animate">
    				<div class="cart-list">
	    				<table class="table">
						    <thead class="thead-primary">
						      <tr class="text-center">
						        <th>&nbsp;</th>
						        <th>&nbsp;</th>
						        <th>{% translate 'Product name' %}</th>
						        <th>{% translate 'Price' %}</th>
						        <th>{% translate 'Quantity' %}</th>
						        <th>{% translate 'Total' %}</th>
						      </tr>
						    </thead>
						    <tbody>
                            {% if cart|length != 0 %}
                                {% for c in cart %}
                                  <tr class="text-center">
                                    <td class="product-remove"><a href="?delete={{ c.product_id }}"><span class="ion-ios-close"></span></a></td>

                                      <td class="image-prod">
                                          <a href="{% url 'product' pk=c.product.id %}"><div class="img" style="background-image:url({{ c.product.image.url }});"></div></a>
                                      </td>

                                    <td class="product-name">
                                        <a href="{% url 'product' pk=c.product.id %}">
                                        <h3>{{ c.product.name }}</h3>
                                        </a>
    {#						        	<p>Far far away, behind the word mountains, far from the countries</p>#}
                                    </td>

                                      <td class="price">${{c.product.cost}}<span class="text-muted small">/{{ c.product.get_measurement_display|lower }}</span></td>

                                <td class="quantity">
                                        <div class="input-group mb-3">
                                        <span class="input-group-btn mr-2">
                                        <button type="button" class="quantity-left-minus btn plus-minus-btn"  data-type="minus" data-field="">
                                            <i class="ion-ios-remove"></i>
                                        </button>
                                        </span>
                                        <input type="text" name="quantity"
                                               class="quantity form-control input-number" value="{{ c.qty }}"
                                               min="{{ c.product.min_qty }}" max="100" product_cost="{{c.product.cost}}">
                                        <span class="input-group-btn ml-2">
                                        <button type="button" class="quantity-right-plus btn plus-minus-btn" data-type="plus" data-field="">
                                             <i class="ion-ios-add"></i>
                                         </button>
                                        </span>
                                    </div>
                                  </td>

                                    <td class="total total_cost">${% widthratio c.qty 1 c.product.cost %}</td>
                                  </tr><!-- END TR-->
                                {% endfor %}
                            {% else %}
                                <tr>
                                <td colspan="6">
                                    {% translate 'There is no products in your cart' %}
                                </td>
                                </tr>
                            {% endif %}


						    </tbody>
						  </table>
					  </div>
    			</div>
    		</div>
            {% if cart|length != 0 %}
    		<div class="row">
                <form action="#" class="col-lg-12 make_offer_form" style="position: relative" method="post">{% csrf_token %}
                    <div class="row">
                    <div class="col-lg-4 mt-5 cart-wrap ftco-animate">
                        <div class="cart-total mb-3">
                            <h3>{% translate 'Shipping details' %}</h3>
                              {{ order_form|crispy }}

                        </div>
    {#    				<p><a href="checkout.html" class="btn btn-primary py-3 px-4">Estimate</a></p>#}
                    </div>
                    <div class="col-lg-4 mt-5 cart-wrap ftco-animate">
                        <div class="cart-total mb-3">
                            <h3>{% translate 'Cart Totals' %}</h3>
                            <p class="d-flex">
                                <span>{% translate 'Subtotal' %}</span>
                                <span id="totals-sub"></span>
                            </p>
                            <p class="d-flex">
                                <span>{% translate 'Discount' %}</span>
                                <span>$0.00</span>
                            </p>
                            <hr>
                            <p class="d-flex total-price">
                                <span>{% translate 'Total' %}</span>
                                <span id="totals-total"></span>
                            </p>
                        </div>
                        <p>
                            <button class="btn btn-primary py-3 px-4">
                                {% translate 'Proceed to Checkout' %}
                            </button>
                        </p>
                    </div>
                    </div>
                </form>
    		</div>
            {% endif %}
			</div>
		</section>
{% endblock %}
{% block mycss %}
    <style>
        .make_offer_form .form-group .form-control {
            padding: 5px;
            text-align: left;
        }
        .make_offer_form button{
            color: #fff !important;
        }
        .make_offer_form button:hover{
            color: #82ae46 !important;
        }
    </style>
{% endblock %}
{% block myjs %}
    <script>
        function calcTotals(){
            var i;
            totals = $('.total_cost');
            sub_total = 0;
            for(i=0; i<totals.length; i++) {
                sub_total += parseInt(totals[i].textContent.replace("$", ""))
            }
            $("#totals-sub").html("$"+sub_total);
            $("#totals-total").html("$"+sub_total)
        }
		$(document).ready(function(){

		   $('.quantity-right-plus').click(function(e){

		        // Stop acting like a button
		        e.preventDefault();
		        // Get the field name
               quant_input = $(this).closest('td.quantity').find('input[name="quantity"]');
		        var quantity = parseInt(quant_input.val());


		        // If is not undefined

		            $(this).closest('td.quantity').find('input[name="quantity"]').attr('value', quantity + 1).change();




		            // Increment

		    });

		     $('.quantity-left-minus').click(function(e){
		        // Stop acting like a button
		        e.preventDefault();
		        // Get the field name
		        quant_input = $(this).closest('td.quantity').find('input[name="quantity"]');
		        var quantity = parseInt(quant_input.val());
		        var min_quantity = parseInt(quant_input.attr('min'));

		        // If is not undefined

                // Increment
                if(quantity>0 && quantity!== min_quantity ){
                    quant_input.attr('value', quantity - 1).change();
                }

		    });

		     $('input[name="quantity"]').change(function () {
                    var product_cost = parseInt($(this).attr('product_cost'));
                    var quantity = parseInt($(this).val());
                    $(this).closest('tr').find('.total_cost').html("$"+quantity*product_cost);
                 calcTotals()
                 }
             );
            calcTotals()
		});
	</script>
{% endblock %}

templates/pages/category.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<section class="ftco-section">
    	<div class="container">
    		<div class="row justify-content-center">
    			<div class="col-md-10 mb-5 text-center">
    				<ul class="product-category">
    					<li><a href="{% url 'category_all' %}" {% if not category %}class="active"{% endif %}>{% translate 'All' %}</a></li>
                        {% for cat in main_cats %}
    					    <li><a href="{% url 'category' pk=cat.id %}" {% if category and category.id == cat.id %}class="active"{% endif %}>{{cat.name}}</a></li>
                        {% endfor %}
    				</ul>
    			</div>
    		</div>
    		<div class="row">
            {% if products.count != 0 %}
                {% for pr in products %}
    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="{% url 'product' pk=pr.id %}" class="img-prod"><img class="img-fluid" src="{{ pr.image.url }}" alt="{{ pr.name }}">
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center">
    						<h3><a href="{% url 'product' pk=pr.id %}">{{ pr.name }}</a></h3>
    						<div class="d-flex">
    							<div class="pricing">
		    						<p class="price"><span class="mr-2">${{ pr.cost }}</span></p>
		    					</div>
	    					</div>
	    					<div class="bottom-area d-flex px-3">
	    						<div class="m-auto d-flex">
	    							<a href="#" class="buy-now d-flex justify-content-center align-items-center mx-1">
	    								<span><i class="ion-ios-cart"></i></span>
	    							</a>
    							</div>
    						</div>
    					</div>
    				</div>
    			</div>
                {% endfor %}
            {% else %}
                <div class="col-md-12 ftco-animate">
                    <div class="alert alert-light" role="alert">
                      {% translate 'There is no any product in this category' %}
                    </div>
                </div>
            {% endif %}
    		</div>
{#    		<div class="row mt-5">#}
{#              <div class="col text-center">#}
{#                <div class="block-27">#}
{#                  <ul>#}
{#                    <li><a href="#">&lt;</a></li>#}
{#                    <li class="active"><span>1</span></li>#}
{#                    <li><a href="#">2</a></li>#}
{#                    <li><a href="#">3</a></li>#}
{#                    <li><a href="#">4</a></li>#}
{#                    <li><a href="#">5</a></li>#}
{#                    <li><a href="#">&gt;</a></li>#}
{#                  </ul>#}
{#                </div>#}
{#              </div>#}
{#            </div>#}
    	</div>
    </section>
{% endblock %}

templates/pages/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
<section class="ftco-section contact-section bg-light">
      <div class="container">
        <div class="row block-12 justify-content-center">
          <div class="col-md-6 order-md-last">
            <form action="#" class="bg-white p-5 contact-form" method="post">{% csrf_token %}
                {{ form|crispy }}
              <div class="d-flex justify-content-between align-items-center">
                  <a href="{% url 'register' %}" class="nav-link">{% translate 'Registering' %}</a>
                <input type="submit" value="{% translate 'Login' %}" class="btn btn-primary py-3 px-5">
              </div>
            </form>

          </div>

        </div>
      </div>
    </section>
{% endblock %}

templates/pages/orders.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load humanize %}
{% load i18n %}
{% block content %}
<section class="ftco-section ftco-cart ftco-no-pt">
			<div class="container">
				<div class="row">
    			<div class="col-md-12 ftco-animate">
                    <h3 class="text-center pt-1">{% translate 'My orders' %}</h3>
    				<div class="cart-list">
	    				<table class="table">
						    <thead class="thead-primary">
						      <tr class="text-center">
						        <th>{% translate 'Order ID' %}</th>
						        <th>{% translate 'Products' %}</th>
						        <th>{% translate 'Date' %}</th>
						        <th>{% translate 'Status' %}</th>
						        <th>{% translate 'Price' %}</th>
						      </tr>
						    </thead>
						    <tbody>
                            {% if user_orders|length != 0 %}
                                {% for o in user_orders %}
                                  <tr class="text-center">
                                    <td class="product-remove">{{ o.id }}</td>
                                    <td class="price">
                                        {% for pr in o.products %}
                                            <img src="{{ pr.product.image.url }}" alt="" width="70px">
                                            {{ pr.name }} - ${{ pr.cost }}
                                            <span class="text-muted ">/{{ pr.product.get_measurement_display|lower }}</span>, {{ pr.qty }}<br>
                                        {% endfor %}
                                    </td>
                                  <td class="quantity">
                                      <span data-toggle="tooltip" data-placement="top" title="{{ o.date }}">{{ o.date|naturaltime }}</span>
                                  </td>

                                    <td class="price">
                                        {{ o.get_status_display }}<br>
                                        {% if o.status == 0 %}
                                            <a href="#" class="btn btn-warning">{% translate 'Make a payment' %}</a>
                                        {% endif %}
                                    </td>

                                    <td class="total total_cost">
                                        ${{ o.total_cost }}
                                    </td>
                                  </tr><!-- END TR-->
                                {% endfor %}
                            {% else %}
                                <tr>
                                <td colspan="6">
                                    {% translate "You haven't made any orders yet" %}
                                </td>
                                </tr>
                            {% endif %}


						    </tbody>
						  </table>
					  </div>
    			</div>
    		</div>
			</div>
		</section>
{% endblock %}

templates/pages/product.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
  <section class="ftco-section ftco-no-pt">
    	<div class="container">
    		<div class="row">
                <div class="col-md-12">
                    <nav aria-label="breadcrumb">
                      <ol class="breadcrumb bg-white">
                        <li class="breadcrumb-item"><a href="{% url 'home' %}">{% translate 'Home' %}</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'category' pk=product.category.id %}">{{ product.category.name }}</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{{product.name}}</li>
                      </ol>
                    </nav>
                </div>
    			<div class="col-lg-6 mb-5 ftco-animate">
    				<a href="{{ product.image.url }}" class="image-popup"><img src="{{ product.image.url }}" class="img-fluid" alt="{{product.name}}"></a>
    			</div>
    			<div class="col-lg-6 product-details pl-md-5 ftco-animate">
    				<h3>{{ product.name }}</h3>
    				<div class="rating d-flex">
                        <p class="text-left mr-4">
                            <a href="#" class="mr-2">{% translate 'In stock' %}</a>
                        </p>
                    </div>
    				<p class="price"><span>${{product.cost}}</span>/ {{ product.get_measurement_display|lower }}</p>
    				<p>{{ product.description }}</p>
                    <form method="post" action="">
                        {% csrf_token %}
                        <input type="hidden" value="{{ product.id }}" name="product_id">
                        <div class="row mt-4">
                            <div class="col-md-6">
                                <div class="form-group d-flex">
                                </div>
                            </div>
                            <div class="w-100"></div>
                            <div class="input-group col-md-6 d-flex mb-3">
                                <span class="input-group-btn mr-2">
                                    <button type="button" class="quantity-left-minus btn plus-minus-btn"  data-type="minus" data-field="">
                                        <i class="ion-ios-remove"></i>
                                    </button>
                                </span>
                                <input type="text" id="quantity" name="quantity" class="form-control input-number" value="{{product.min_qty}}" min="{{product.min_qty}}">
                                <span class="input-group-btn ml-2">
                                    <button type="button" class="quantity-right-plus btn plus-minus-btn" data-type="plus" data-field="">
                                         <i class="ion-ios-add"></i>
                                     </button>
                                </span>
                            </div>
                            <div class="w-100"></div>
                            <div class="col-md-12">
                                <p style="color: #000;">{% translate 'Minimum order' %}: {{product.min_qty}} {{ product.get_measurement_display }}</p>
                            </div>
                        </div>
                        <p><button class="btn btn-black py-3 px-5">{% translate 'Add to Cart' %}</button></p>
                        {% if product_added_tocart %}
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {% translate 'Product added to cart.' %} <a href="{% url 'cart' %}">{% translate 'Go to the cart' %}</a>
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        {% endif %}
                    </form>
    			</div>
    		</div>
    	</div>
    </section>

    <section class="ftco-section ftco-no-pt">
    	<div class="container">
				<div class="row justify-content-center mb-3 pb-3">
          <div class="col-md-12 heading-section text-center ftco-animate">
          	<span class="subheading">{% translate 'Products' %}</span>
            <h2 class="mb-4">{% translate 'Related Products' %}</h2>
{#            <p>Far far away, behind the word mountains, far from the Uzbekistan</p>#}
          </div>
        </div>
    	</div>
    	<div class="container">
    		<div class="row">
    			{% for prd in related %}
    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="{% url 'product' pk=prd.id %}" class="img-prod"><img class="img-fluid" src="{{ prd.image.url }}" alt="{{ prd.name }}">
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center">
    						<h3><a href="#">{{ prd.name }}</a></h3>
    						<div class="d-flex">
    							<div class="pricing">
		    						<p class="price"><span class="mr-2">${{prd.cost}}</span></p>
		    					</div>
	    					</div>
	    					<div class="bottom-area d-flex px-3">
	    						<div class="m-auto d-flex">
	    							<a href="{% url 'product' pk=prd.id %}" class="buy-now d-flex justify-content-center align-items-center mx-1">
	    								<span><i class="ion-ios-cart"></i></span>
	    							</a>
    							</div>
    						</div>
    					</div>
    				</div>
    			</div>
                {% endfor %}

    		</div>
    	</div>
    </section>

{% endblock %}

{% block myjs %}
    <script>
		$(document).ready(function(){

		   $('.quantity-right-plus').click(function(e){

		        // Stop acting like a button
		        e.preventDefault();
		        // Get the field name
		        var quantity = parseInt($('#quantity').val());

		        // If is not undefined

		            $('#quantity').val(quantity + 1);


		            // Increment

		    });

		     $('.quantity-left-minus').click(function(e){
		        // Stop acting like a button
		        e.preventDefault();
		        // Get the field name
		        var quantity = parseInt($('#quantity').val());

		        // If is not undefined

                // Increment
                if(quantity>0 && quantity!== {{product.min_qty}} ){
                    $('#quantity').val(quantity - 1);
                }
		    });

		});
	</script>
{% endblock %}

templates/pages/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
<section class="ftco-section contact-section bg-light">
      <div class="container">
        <div class="row block-12 justify-content-center">
          <div class="col-md-6 order-md-last">
            <form action="#" class="bg-white p-5 contact-form" method="post">{% csrf_token %}
                {{ form|crispy }}
              <div class="d-flex justify-content-between align-items-center">
                  <a href="{% url 'login' %}" class="nav-link">{% translate 'Login' %}</a>
                <input type="submit" value="{% translate 'Register' %}" class="btn btn-primary py-3 px-5">
              </div>
            </form>

          </div>

        </div>
      </div>
    </section>
{% endblock %}